// LuminaVaultClient/LuminaVaultClient/Features/Auth/Phone/Country.swift
// HER-141: bundled country list for the phone OTP picker. Self-contained
// rather than pulled from PhoneNumberKit's private MetadataManager so the
// picker UI can render flag + dial code without depending on PNK internals.
import Foundation

struct Country: Hashable, Identifiable, Sendable {
    let isoCode: String  // ISO 3166-1 alpha-2, e.g. "US"
    let dialCode: String // E.164 country code with leading "+", e.g. "+1"
    let name: String

    var id: String { isoCode }

    /// Renders the country's regional-indicator flag emoji from the ISO code.
    var flag: String {
        isoCode.unicodeScalars
            .compactMap { UnicodeScalar(127397 + Int($0.value)) }
            .map { String($0) }
            .joined()
    }
}

enum Countries {
    /// Alphabetised by display name. Covers every UN member + common
    /// territories. Dial codes follow ITU E.164.
    static let all: [Country] = [
        Country(isoCode: "AF", dialCode: "+93",  name: "Afghanistan"),
        Country(isoCode: "AL", dialCode: "+355", name: "Albania"),
        Country(isoCode: "DZ", dialCode: "+213", name: "Algeria"),
        Country(isoCode: "AD", dialCode: "+376", name: "Andorra"),
        Country(isoCode: "AO", dialCode: "+244", name: "Angola"),
        Country(isoCode: "AR", dialCode: "+54",  name: "Argentina"),
        Country(isoCode: "AM", dialCode: "+374", name: "Armenia"),
        Country(isoCode: "AU", dialCode: "+61",  name: "Australia"),
        Country(isoCode: "AT", dialCode: "+43",  name: "Austria"),
        Country(isoCode: "AZ", dialCode: "+994", name: "Azerbaijan"),
        Country(isoCode: "BH", dialCode: "+973", name: "Bahrain"),
        Country(isoCode: "BD", dialCode: "+880", name: "Bangladesh"),
        Country(isoCode: "BY", dialCode: "+375", name: "Belarus"),
        Country(isoCode: "BE", dialCode: "+32",  name: "Belgium"),
        Country(isoCode: "BZ", dialCode: "+501", name: "Belize"),
        Country(isoCode: "BJ", dialCode: "+229", name: "Benin"),
        Country(isoCode: "BT", dialCode: "+975", name: "Bhutan"),
        Country(isoCode: "BO", dialCode: "+591", name: "Bolivia"),
        Country(isoCode: "BA", dialCode: "+387", name: "Bosnia and Herzegovina"),
        Country(isoCode: "BW", dialCode: "+267", name: "Botswana"),
        Country(isoCode: "BR", dialCode: "+55",  name: "Brazil"),
        Country(isoCode: "BN", dialCode: "+673", name: "Brunei"),
        Country(isoCode: "BG", dialCode: "+359", name: "Bulgaria"),
        Country(isoCode: "BF", dialCode: "+226", name: "Burkina Faso"),
        Country(isoCode: "BI", dialCode: "+257", name: "Burundi"),
        Country(isoCode: "KH", dialCode: "+855", name: "Cambodia"),
        Country(isoCode: "CM", dialCode: "+237", name: "Cameroon"),
        Country(isoCode: "CA", dialCode: "+1",   name: "Canada"),
        Country(isoCode: "CV", dialCode: "+238", name: "Cape Verde"),
        Country(isoCode: "TD", dialCode: "+235", name: "Chad"),
        Country(isoCode: "CL", dialCode: "+56",  name: "Chile"),
        Country(isoCode: "CN", dialCode: "+86",  name: "China"),
        Country(isoCode: "CO", dialCode: "+57",  name: "Colombia"),
        Country(isoCode: "KM", dialCode: "+269", name: "Comoros"),
        Country(isoCode: "CG", dialCode: "+242", name: "Congo"),
        Country(isoCode: "CD", dialCode: "+243", name: "Congo (DRC)"),
        Country(isoCode: "CR", dialCode: "+506", name: "Costa Rica"),
        Country(isoCode: "CI", dialCode: "+225", name: "Côte d'Ivoire"),
        Country(isoCode: "HR", dialCode: "+385", name: "Croatia"),
        Country(isoCode: "CU", dialCode: "+53",  name: "Cuba"),
        Country(isoCode: "CY", dialCode: "+357", name: "Cyprus"),
        Country(isoCode: "CZ", dialCode: "+420", name: "Czech Republic"),
        Country(isoCode: "DK", dialCode: "+45",  name: "Denmark"),
        Country(isoCode: "DJ", dialCode: "+253", name: "Djibouti"),
        Country(isoCode: "DO", dialCode: "+1",   name: "Dominican Republic"),
        Country(isoCode: "EC", dialCode: "+593", name: "Ecuador"),
        Country(isoCode: "EG", dialCode: "+20",  name: "Egypt"),
        Country(isoCode: "SV", dialCode: "+503", name: "El Salvador"),
        Country(isoCode: "ER", dialCode: "+291", name: "Eritrea"),
        Country(isoCode: "EE", dialCode: "+372", name: "Estonia"),
        Country(isoCode: "ET", dialCode: "+251", name: "Ethiopia"),
        Country(isoCode: "FJ", dialCode: "+679", name: "Fiji"),
        Country(isoCode: "FI", dialCode: "+358", name: "Finland"),
        Country(isoCode: "FR", dialCode: "+33",  name: "France"),
        Country(isoCode: "GA", dialCode: "+241", name: "Gabon"),
        Country(isoCode: "GM", dialCode: "+220", name: "Gambia"),
        Country(isoCode: "GE", dialCode: "+995", name: "Georgia"),
        Country(isoCode: "DE", dialCode: "+49",  name: "Germany"),
        Country(isoCode: "GH", dialCode: "+233", name: "Ghana"),
        Country(isoCode: "GR", dialCode: "+30",  name: "Greece"),
        Country(isoCode: "GT", dialCode: "+502", name: "Guatemala"),
        Country(isoCode: "GN", dialCode: "+224", name: "Guinea"),
        Country(isoCode: "GY", dialCode: "+592", name: "Guyana"),
        Country(isoCode: "HT", dialCode: "+509", name: "Haiti"),
        Country(isoCode: "HN", dialCode: "+504", name: "Honduras"),
        Country(isoCode: "HK", dialCode: "+852", name: "Hong Kong"),
        Country(isoCode: "HU", dialCode: "+36",  name: "Hungary"),
        Country(isoCode: "IS", dialCode: "+354", name: "Iceland"),
        Country(isoCode: "IN", dialCode: "+91",  name: "India"),
        Country(isoCode: "ID", dialCode: "+62",  name: "Indonesia"),
        Country(isoCode: "IR", dialCode: "+98",  name: "Iran"),
        Country(isoCode: "IQ", dialCode: "+964", name: "Iraq"),
        Country(isoCode: "IE", dialCode: "+353", name: "Ireland"),
        Country(isoCode: "IL", dialCode: "+972", name: "Israel"),
        Country(isoCode: "IT", dialCode: "+39",  name: "Italy"),
        Country(isoCode: "JM", dialCode: "+1",   name: "Jamaica"),
        Country(isoCode: "JP", dialCode: "+81",  name: "Japan"),
        Country(isoCode: "JO", dialCode: "+962", name: "Jordan"),
        Country(isoCode: "KZ", dialCode: "+7",   name: "Kazakhstan"),
        Country(isoCode: "KE", dialCode: "+254", name: "Kenya"),
        Country(isoCode: "KW", dialCode: "+965", name: "Kuwait"),
        Country(isoCode: "KG", dialCode: "+996", name: "Kyrgyzstan"),
        Country(isoCode: "LA", dialCode: "+856", name: "Laos"),
        Country(isoCode: "LV", dialCode: "+371", name: "Latvia"),
        Country(isoCode: "LB", dialCode: "+961", name: "Lebanon"),
        Country(isoCode: "LR", dialCode: "+231", name: "Liberia"),
        Country(isoCode: "LY", dialCode: "+218", name: "Libya"),
        Country(isoCode: "LI", dialCode: "+423", name: "Liechtenstein"),
        Country(isoCode: "LT", dialCode: "+370", name: "Lithuania"),
        Country(isoCode: "LU", dialCode: "+352", name: "Luxembourg"),
        Country(isoCode: "MO", dialCode: "+853", name: "Macao"),
        Country(isoCode: "MG", dialCode: "+261", name: "Madagascar"),
        Country(isoCode: "MW", dialCode: "+265", name: "Malawi"),
        Country(isoCode: "MY", dialCode: "+60",  name: "Malaysia"),
        Country(isoCode: "MV", dialCode: "+960", name: "Maldives"),
        Country(isoCode: "ML", dialCode: "+223", name: "Mali"),
        Country(isoCode: "MT", dialCode: "+356", name: "Malta"),
        Country(isoCode: "MR", dialCode: "+222", name: "Mauritania"),
        Country(isoCode: "MU", dialCode: "+230", name: "Mauritius"),
        Country(isoCode: "MX", dialCode: "+52",  name: "Mexico"),
        Country(isoCode: "MD", dialCode: "+373", name: "Moldova"),
        Country(isoCode: "MC", dialCode: "+377", name: "Monaco"),
        Country(isoCode: "MN", dialCode: "+976", name: "Mongolia"),
        Country(isoCode: "ME", dialCode: "+382", name: "Montenegro"),
        Country(isoCode: "MA", dialCode: "+212", name: "Morocco"),
        Country(isoCode: "MZ", dialCode: "+258", name: "Mozambique"),
        Country(isoCode: "MM", dialCode: "+95",  name: "Myanmar"),
        Country(isoCode: "NA", dialCode: "+264", name: "Namibia"),
        Country(isoCode: "NP", dialCode: "+977", name: "Nepal"),
        Country(isoCode: "NL", dialCode: "+31",  name: "Netherlands"),
        Country(isoCode: "NZ", dialCode: "+64",  name: "New Zealand"),
        Country(isoCode: "NI", dialCode: "+505", name: "Nicaragua"),
        Country(isoCode: "NE", dialCode: "+227", name: "Niger"),
        Country(isoCode: "NG", dialCode: "+234", name: "Nigeria"),
        Country(isoCode: "KP", dialCode: "+850", name: "North Korea"),
        Country(isoCode: "MK", dialCode: "+389", name: "North Macedonia"),
        Country(isoCode: "NO", dialCode: "+47",  name: "Norway"),
        Country(isoCode: "OM", dialCode: "+968", name: "Oman"),
        Country(isoCode: "PK", dialCode: "+92",  name: "Pakistan"),
        Country(isoCode: "PA", dialCode: "+507", name: "Panama"),
        Country(isoCode: "PG", dialCode: "+675", name: "Papua New Guinea"),
        Country(isoCode: "PY", dialCode: "+595", name: "Paraguay"),
        Country(isoCode: "PE", dialCode: "+51",  name: "Peru"),
        Country(isoCode: "PH", dialCode: "+63",  name: "Philippines"),
        Country(isoCode: "PL", dialCode: "+48",  name: "Poland"),
        Country(isoCode: "PT", dialCode: "+351", name: "Portugal"),
        Country(isoCode: "PR", dialCode: "+1",   name: "Puerto Rico"),
        Country(isoCode: "QA", dialCode: "+974", name: "Qatar"),
        Country(isoCode: "RO", dialCode: "+40",  name: "Romania"),
        Country(isoCode: "RU", dialCode: "+7",   name: "Russia"),
        Country(isoCode: "RW", dialCode: "+250", name: "Rwanda"),
        Country(isoCode: "SA", dialCode: "+966", name: "Saudi Arabia"),
        Country(isoCode: "SN", dialCode: "+221", name: "Senegal"),
        Country(isoCode: "RS", dialCode: "+381", name: "Serbia"),
        Country(isoCode: "SC", dialCode: "+248", name: "Seychelles"),
        Country(isoCode: "SL", dialCode: "+232", name: "Sierra Leone"),
        Country(isoCode: "SG", dialCode: "+65",  name: "Singapore"),
        Country(isoCode: "SK", dialCode: "+421", name: "Slovakia"),
        Country(isoCode: "SI", dialCode: "+386", name: "Slovenia"),
        Country(isoCode: "SO", dialCode: "+252", name: "Somalia"),
        Country(isoCode: "ZA", dialCode: "+27",  name: "South Africa"),
        Country(isoCode: "KR", dialCode: "+82",  name: "South Korea"),
        Country(isoCode: "SS", dialCode: "+211", name: "South Sudan"),
        Country(isoCode: "ES", dialCode: "+34",  name: "Spain"),
        Country(isoCode: "LK", dialCode: "+94",  name: "Sri Lanka"),
        Country(isoCode: "SD", dialCode: "+249", name: "Sudan"),
        Country(isoCode: "SR", dialCode: "+597", name: "Suriname"),
        Country(isoCode: "SE", dialCode: "+46",  name: "Sweden"),
        Country(isoCode: "CH", dialCode: "+41",  name: "Switzerland"),
        Country(isoCode: "SY", dialCode: "+963", name: "Syria"),
        Country(isoCode: "TW", dialCode: "+886", name: "Taiwan"),
        Country(isoCode: "TJ", dialCode: "+992", name: "Tajikistan"),
        Country(isoCode: "TZ", dialCode: "+255", name: "Tanzania"),
        Country(isoCode: "TH", dialCode: "+66",  name: "Thailand"),
        Country(isoCode: "TL", dialCode: "+670", name: "Timor-Leste"),
        Country(isoCode: "TG", dialCode: "+228", name: "Togo"),
        Country(isoCode: "TT", dialCode: "+1",   name: "Trinidad and Tobago"),
        Country(isoCode: "TN", dialCode: "+216", name: "Tunisia"),
        Country(isoCode: "TR", dialCode: "+90",  name: "Turkey"),
        Country(isoCode: "TM", dialCode: "+993", name: "Turkmenistan"),
        Country(isoCode: "UG", dialCode: "+256", name: "Uganda"),
        Country(isoCode: "UA", dialCode: "+380", name: "Ukraine"),
        Country(isoCode: "AE", dialCode: "+971", name: "United Arab Emirates"),
        Country(isoCode: "GB", dialCode: "+44",  name: "United Kingdom"),
        Country(isoCode: "US", dialCode: "+1",   name: "United States"),
        Country(isoCode: "UY", dialCode: "+598", name: "Uruguay"),
        Country(isoCode: "UZ", dialCode: "+998", name: "Uzbekistan"),
        Country(isoCode: "VE", dialCode: "+58",  name: "Venezuela"),
        Country(isoCode: "VN", dialCode: "+84",  name: "Vietnam"),
        Country(isoCode: "YE", dialCode: "+967", name: "Yemen"),
        Country(isoCode: "ZM", dialCode: "+260", name: "Zambia"),
        Country(isoCode: "ZW", dialCode: "+263", name: "Zimbabwe"),
    ]

    /// Locale-derived default; falls back to US if the device region isn't
    /// in our list (e.g. unusual territory codes).
    static let `default`: Country = {
        let region = Locale.current.region?.identifier ?? "US"
        return all.first { $0.isoCode == region } ?? all.first { $0.isoCode == "US" }!
    }()
}
